#pragma once

namespace CLASS {
	enum TYPE { TILE_CLASS, ARCH_CLASS, MONSTER_CLASS, LINE_CLASS, END_CLASS };
	enum BUTTON_UI {PLAY_BUTTON, OPTION_BUTTON, EXIT_BUTTON, BUTTON_END};
}

namespace OBJECT{
	enum TYPE { TILE_OBJ, ARCHITECTURE_OBJ, PLAYER_OBJ, UI_OBJ, MOUSE_OBJ, END_OBJ };
	enum STATE {};
	enum MAP_RENDER_SORT{};
}

namespace SCENE {
	enum TYPE { LOGO_SCENE, TOWN_SCENE, STAGE1_SCENE, STAGE2_SCENE, STAGE3_SCENE, STAGE4_SCENE, 
		BOSS1_SCENE, BOSS2_SCENE, END_SCENE };
}